### ISSUE TITLE
to ease migration of OSGi ConfigAdmin apps to kubernetes/openshift it'd be nice to have a ConfigMap based ConfigAdmin implementation

### ISSUE THREAD

**Issue by jstrachan** [jboss-fuse/fabric8#685]
where a named ConfigMap could be watched; any changes in it then override the Config admin values for real time updates to the JVMs.

Then folks who wanna reconfigure OSGI config admin stuff on the fly can just update the ConfigMap entry directly

**Comment by jstrachan** [comment]
FWIW there's a similar idea here for Spring Boot: https://github.com/fabric8io/spring-cloud-kubernetes#configmap-propertysource

Note that you can mount items from a ConfigMap to files. The issue for ConfigAdmin is that there's an arbitrary and possibly dynamic set of files; and its a bit painful mapping each entry file by file.

So just watching all entries in a ConfigMap is kinda easier for the user ;) Its then just a single bundle/feature and it'll just work without the user having to mess with their kubernetes/openshift manifests etc

**Comment by lburgazzoli** [comment]
[there is](https://github.com/fabric8io/fabric8/tree/master/components/fabric8-karaf/fabric8-karaf-cm) a basic support for ConfigAdmin now in fabric8 which provide a custom persistence manager that uses ConfigMap as backend.

To bind a ConfigMap to a pid, you only need to set a label named pid whith the pid of your bundle as value, like

``` yaml
kind: ConfigMap
apiVersion: v1
metadata:
    name: map1
    namespace: default
    labels:
        pid: com.mycompany.bundle.1
data:
    example.property.1: hello
    example.property.2: world
```

Watching a configmap for changes is in progress.
